baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'О Проекте'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Журнал'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Участники'
    pageRef = '/participants'
    weight = 30

  [[menus.main]]
    name = 'Ресурсы'
    pageRef = '/external_sources'
    weight = 40



[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
